name: "alloc"
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  basic:
    runs-on: [self-hosted, os]
    timeout-minutes: 1
    name: "Basic checks"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Check that branch has name 'alloc'"
        run: |
          test "${GITHUB_HEAD_REF##*/}" = "alloc"
      - name: "Lint source code"
        run: |
          clang-format --dry-run -Werror */*.c */*.h 2>clang-format.log || status=$?
          if [[ -n $status ]]; then
            cat clang-format.log |
              grep 'error:' |
              perl -pe 's/^((.*?):(.*?):(.*?):.*)$/::error file=\2,line=\3,col=\4::\1/g'
            exit $status
          fi
      - name: "Check description"
        run: |
          hours=$(echo "$GITHUB_PR" | sed -n 3p | tr -d '[:space:]')
          if [[ "$hours" == +([[:digit:]]) ]]; then
            echo "Hours spent: $hours"
          else
            echo "::error Please fill in hours spent into pull request description"
            exit 1
          fi
        env:
          GITHUB_PR: ${{ github.event.pull_request.body }}
      - name: "Upload logs"
        uses: actions/upload-artifact@v2
        with:
          name: clang-format.log
          path: clang-format.log
        if: ${{ failure() }}
  tests:
    needs: basic
    runs-on: [self-hosted, os]
    timeout-minutes: 15
    name: "Required tests"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Run tests"
        run: ./grade
      - name: "Upload logs"
        uses: actions/upload-artifact@v2
        with:
          name: xv6.out
          path: xv6.out.*
        if: ${{ failure() }}
